Add filter for polarization and additional calibration/noise/rfi downloads
avalentino/asfsmd pull request #3
Opened 2022-10-28 17:04 UTC by scottstanie

This adds two functions:
1. Filter the download by polarization (e.g. so you can grab only 3 'vv' files instead of the 6 for vv/vh)
2. Download the calibration, noise, and RFI xml files 
 
I also made a separate branch to further filter to a single subswath by checking `iw{number}`, but these are the additions I've already found useful when testing https://github.com/opera-adt/s1-reader

2022-10-29 16:13 UTC, avalentino requested changes
Dear @scottstanie,
thanks a lot for submitting this PR.
It goes in the direction of what I had in mind, i.e. to evolve the tool to be able to download arbitrary product components.
I have put some comments to your PR requesting few changes.

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +                              do_rfi=False):
In order to have a generic function probably it would be better to add only one parameter, the list of `patterns` and move the logic to generate the list of patterns form the CLI options in a separate function.
Moreover the could be renamed into a more generic `download_components_from_urls`.

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +    if urls is None:
The additional `urls` parameter is not really necessary.
One could always use directly the function above that accepts `urls` as input.

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +        "--polarization",
I would recommend to use one short option (single dash) and one long option: e.g. `-p` and  `--pol`.

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +        action="store_true",
same as above: `-c` and `--cal`

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +        action="store_true",
`-n`, `--noise`

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +        action="store_true",
`-r`, `--rfi`

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +        "--urls",
This should be alternative to `inputs`.
Maybe we could convert the `--urls` parameter into a flag that specifies how `inputs` shall be interpreted.

2022-10-29 16:13 UTC, avalentino commented on asfsmd.py
> +            inputs = [p.replace(".zip", "").replace(".SAFE", "") for p in args.inputs]
Not clear what is the use-case for this.

2022-11-01 15:06 UTC, scottstanie commented on asfsmd.py
> +                              do_rfi=False):
good idea, i'll try to redo these arguments in that style

2022-11-01 15:06 UTC, scottstanie commented on asfsmd.py
> +    if urls is None:
👍 yes that would be less weird than this, i'll remove urls here

2022-11-01 15:07 UTC, scottstanie commented on asfsmd.py
> +        "--polarization",
Any suggestion on what to make `--password` into if we use `-p` here? that was what led me to do `--pol` as the short option

2022-11-01 15:10 UTC, scottstanie commented on asfsmd.py
> +            inputs = [p.replace(".zip", "").replace(".SAFE", "") for p in args.inputs]
I added this because my first two thoughts at what the `product` should be for the ASF search was something ending in `.zip`" (since it's the actual product you download), or ending in `.SAFE` (since it's how ESA packages the product).
It's really a workaround to make the ASF query more accommodating (why wouldn't it accept if you pass in the product ending in zip? there's no confusion with some other product) but I can remove it if you'd like and bring my suggestion/gripe to the ASF repo

2022-11-01 16:40 UTC, avalentino commented on asfsmd.py
> +        "--polarization",
sorry, forgot about that.
Maybe we could just stay with the long option.

2022-11-01 16:45 UTC, avalentino commented on asfsmd.py
> +            inputs = [p.replace(".zip", "").replace(".SAFE", "") for p in args.inputs]
No, I have no problems with it, I was just curious.

2022-11-08 05:54 UTC, avalentino requested changes

2022-11-08 05:54 UTC, avalentino commented on asfsmd.py
> +        choices=["vv", "vh"],
Please do not forget "hv" and "hh"

2022-11-08 15:58 UTC, scottstanie commented on asfsmd.py
> +        choices=["vv", "vh"],
whoops, thank you! added

2022-11-08 16:12 UTC, avalentino approved these changes

2022-11-08 16:13 UTC, avalentino commented
Thanks @scottstanie

2022-11-08 16:13 UTC, merged